# Baseado na imagem Python 3.9 slim
FROM python:3.9-slim

WORKDIR /app

COPY files/movielist.csv /app/movielist.csv
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-m", "unittest", "tests.test_api"]
